image: node:latest

stages:
  - build
  - deploy

build_react:
  stage: build

  script:
    - echo "====== Install dependencies ======"
    - npm i
    - echo "====== Build react ======"
    - gulp

  artifacts:
    name: panel-build
    paths:
      - build

deploy_react:
  stage: deploy
  script:
    - echo "====== Deploy to production server ======"
    - apt-get update && apt-get upgrade
    - echo "====== Add target servers secret key ======"
    - mkdir ~/.ssh
    - echo $TARGET_SERVER_SECRET_KEY_BASE64 | base64 -d > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh && chmod 600 ~/.ssh/*
    - echo "====== Test ssh connection ======"
    - ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -T "$TARGET_SERVER_USER_HOST"
    - echo "====== Install rsync on remote server ======"
    - ssh -T -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null  "$TARGET_SERVER_USER_HOST" 'sudo apt-get install rsync -y'
    - echo "====== Sync local and remote directory ======"
    # Ending "/" in string "./build/" is important!
    - rsync -azPq -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" --delete ./build/ "$TARGET_SERVER_USER_HOST:$TARGET_SERVER_PATH"
  only:
  - master
