image: node:latest

stages:
  - build
  - deploy

build_react:
  stage: build

  script:
    - echo "====== Install dependencies ======"
    - npm i
    - echo "====== Build react ======"
    - gulp

  artifacts:
    name: panel-build
    paths:
      - build

deploy:
  image: alpine
  stage: deploy
  script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_dsa
    - chmod 600 ~/.ssh/id_dsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -rav --delete dist/ gitlab-runner@ronzertnert.me:/home/
