image: alpine

before_script:
- apk update
- apk add doxygen
- apk add ttf-freefont graphviz
- apk add 
- apk add openssh-client

stages:
  - deploy

deploy to production:
  stage: deploy
  environment: production
  only:
    - master
  script: "rsync-script.sh saltman@ronzertnert.me:jumpcut-web /gulp/jumpcut-web"
