build_react:
  image: node:latest
  
stage:
  - build

  script:
    - echo "====== Install dependencies ======"
    - npm i
    - echo "====== Build react ======"
    - gulp

  artifacts:
    name: panel-build
    paths:
      - jumpcut-web

deploy:
  image: alpine:latest

before_script:
- apk update
- apk add doxygen
- apk add ttf-freefont graphviz
- apk add 
- apk add openssh-client

stages:
  - deploy

deploy to production:
  stage: deploy
  environment: production
  only:
    - master
  script: rsync-script.sh saltman@ronzertnert.me:jumpcut-web /gulp/jumpcut-web

