sudo: false
language: python
cache: pip
python:
    - "3.4"
    - "3.5"
    - "3.6"
env:
  - DJANGO=2.0.4
  
install:
    - "pip install -r backend/requirements.txt"
    - "pip install -r backend/testing_requirements.txt"
    - "pip install coverage"
script:
    - "flake8 ./backend/src/"
    - "./backend/src/manage.py makemigrations"
    - "./backend/src/manage.py migrate"
    - "coverage run ./backend/src/manage.py test -v 3"
after_success:
    - coverage report -m
 
