sudo: false
language: python
python:
    - "3.4"
install:
    - "pip install -r requirements.txt"
    - "pip install -r testing_requirements.txt"
    - "pip install coveralls"
script:
    - "flake8 ."
    - "./streisand/manage.py makemigrations"
    - "./streisand/manage.py migrate"
    - "coverage run ./streisand/manage.py test streisand"
after_success:
    - coveralls
