sudo: false
language: python
cache: pip
python:
    - "3.4"
    - "3.5"
    - "3.6"
env:
  - DJANGO=2.0.4
install:
    - "cd backend"
    - "pip install -r requirements.txt"
    - "pip install -r testing_requirements.txt"
    - "pip install coveralls"
script:
    - "flake8 src/"
    - "./src/manage.py makemigrations"
    - "./src/manage.py migrate"
    - "coverage run ./src/manage.py test -v 3"
after_success:
    - coverage report -m
 
