# Docker compose for the dev server
#
version: '3'

services:
    db:
        image: postgres:9.5
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_DB: jumpcut
        volumes:
            - dbdata:/var/lib/postgresql/data
        restart: always
    redis:
        image: redis:3.2
        restart: always
    www:
        image: registry.ronzertnert.me/jumpcut/jumpcut:develop
        depends_on:
            - db
            - redis
        environment:
            - DATABASE_URL=postgres://postgres:password@db:5432/jumpcut
            - REDIS_URL=redis://redis:6379
            - SECRET_KEY=changeme
        ports:
            - "8000:80"
        restart: always
    tracker:
        image: registry.ronzertnert.me/jumpcut/jumpcut:develop
        depends_on:
            - db
            - redis
        environment:
            - DATABASE_URL=postgres://postgres:${DB_PASSWORD}@db:5432/jumpcut
            - REDIS_URL=redis://redis:6379
            - SECRET_KEY=${SECRET_KEY}
            - TRACKER
        ports:
            - "7070:80"
        restart: always
    celery:
        image: registry.ronzertnert.me/jumpcut/jumpcut:develop
        command: celery worker --workdir /code/src -A streisand -l info
        depends_on:
            - db
            - redis
        environment:
            - DATABASE_URL=postgres://postgres:${DB_PASSWORD}@db:5432/jumpcut
            - REDIS_URL=redis://redis:6379
            - SECRET_KEY=${SECRET_KEY}
        restart: always
volumes:
    dbdata:
